### ISSUE TITLE
Indexing issue

### ISSUE THREAD

**Issue by grigzy28** [team-exor/eiquidus#54]
Had to do a reindex of an explorer and getting this error now.  Of course it was able to index it way back in time at some point but now it throws this error.  I did do an update-explorer to see if there was any updates before posting this and there were none.

Social Send - 
https://github.com/SocialSend/SocialSend
addnode 136.41.0.101
addnode 172.221.130.108

Thanks

```
78869: bbe38d2019ee5201699296904e9afcae0dc0b4cfcf6c7ead727a7a6e1135bdda
78869: 206491a52156bdcc273059d201b3d5c7016939fe918f24e505205e546d5d9776
/root/sendexplorer/lib/explorer.js:1087
    module.exports.syncLoop(array.length, function (loop) {
                                                   ^

RangeError: Maximum call stack size exceeded
    at /root/sendexplorer/lib/explorer.js:1087:52
    at Object.next (/root/sendexplorer/lib/explorer.js:845:13)
    at /root/sendexplorer/lib/explorer.js:1096:14
    at Object.next (/root/sendexplorer/lib/explorer.js:845:13)
    at /root/sendexplorer/lib/explorer.js:1096:14
    at Object.next (/root/sendexplorer/lib/explorer.js:845:13)
    at /root/sendexplorer/lib/explorer.js:1096:14
    at Object.next (/root/sendexplorer/lib/explorer.js:845:13)
    at /root/sendexplorer/lib/explorer.js:1096:14
    at Object.next (/root/sendexplorer/lib/explorer.js:845:13)
    at /root/sendexplorer/lib/explorer.js:1096:14
    at Object.next (/root/sendexplorer/lib/explorer.js:845:13)
    at /root/sendexplorer/lib/explorer.js:1096:14
    at Object.next (/root/sendexplorer/lib/explorer.js:845:13)
    at /root/sendexplorer/lib/explorer.js:1096:14
    at Object.next (/root/sendexplorer/lib/explorer.js:845:13)

Node.js v20.5.1

root@shawnvpslenexa241:~/sendexplorer# npm run sync-blocks

Setting 'block_page.multi_algorithm' is missing. Loading default value
Setting 'markets_page.exchanges.nonkyc' is missing. Loading default value
Setting 'claim_address_page.enable_captcha' is missing. Loading default value
Setting 'captcha' is missing. Loading default value
Setting 'plugins' is missing. Loading default value
Script launched with pid: 1971866
Syncing blocks.. Please wait..
/root/sendexplorer/lib/explorer.js:860
        return index - 1;
        ^

RangeError: Maximum call stack size exceeded
    at Object.iteration (/root/sendexplorer/lib/explorer.js:860:9)
    at /root/sendexplorer/lib/explorer.js:1088:20
    at Object.next (/root/sendexplorer/lib/explorer.js:845:13)
    at /root/sendexplorer/lib/explorer.js:1096:14
    at Object.next (/root/sendexplorer/lib/explorer.js:845:13)
    at /root/sendexplorer/lib/explorer.js:1096:14
    at Object.next (/root/sendexplorer/lib/explorer.js:845:13)
    at /root/sendexplorer/lib/explorer.js:1096:14
    at Object.next (/root/sendexplorer/lib/explorer.js:845:13)
    at /root/sendexplorer/lib/explorer.js:1096:14
    at Object.next (/root/sendexplorer/lib/explorer.js:845:13)
    at /root/sendexplorer/lib/explorer.js:1096:14
    at Object.next (/root/sendexplorer/lib/explorer.js:845:13)
    at /root/sendexplorer/lib/explorer.js:1096:14
    at Object.next (/root/sendexplorer/lib/explorer.js:845:13)
    at /root/sendexplorer/lib/explorer.js:1096:14

Node.js v20.5.1
```

**Comment by grigzy28** [comment]
Sorry forgot to see closed issues first and saw that I had a previous issue with this.  Long time ago :)

**Comment by joeuhren** [comment]
Just a note that as of today the "RangeError: Maximum call stack size exceeded" error is now being handled directly by the sync script and it should no longer be necessary to manually add the `--stack-size=[SIZE]` argument to the block sync cmd. Commit: https://github.com/team-exor/eiquidus/commit/0b0ef817f187584484e193ab115f6bdd7ed7ea4e

Now when the error occurs, the sync is smart enough to capture the error and automatically restart itself with a larger stack size and continue from where it left off. This new "elastic stack size" feature will help keep memory usage lower by not needing to permanently increase the stack size memory every time the sync script is run.

I believe I caught all the places that could trigger the error, but please create a new github issue to let me know if you are still experiencing this error with the new update in place.

As always, you can run the `npm run update-explorer` cmd to merge the latest explorer changes to take advantage of this and other updates and fixes.
